[package]
name = "pin-project-lite"
version = "0.2.4"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/pin-project-lite"
documentation = "https://docs.rs/pin-project-lite"
keywords = ["pin", "macros"]
categories = ["no-std", "rust-patterns"]
exclude = ["/.github", "/scripts"]
description = """
A lightweight version of pin-project written with declarative macros.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = [
    "tests/doc",
    "tests/no-core",
    "tests/no-std",
]

[dev-dependencies]
macrotest = { version = "1.0.7", git = "https://github.com/taiki-e/macrotest.git", rev = "acd8b3c" }
rustversion = "1"
static_assertions = "1"
trybuild = "1"
